branches:
  only:
    - master

language: python
python:
  - "2.7"
  - "3.4"
# TBD after fix https://bitbucket.org/pytest-dev/pytest/pull-request/296/astcall-signature-changed-on-35/diff
#  - "nightly"

install:
  - pip install -U pip
  - pip install -U -r test_requirements.txt

before_script:
  - pip install -U -e .
script:
  - py.test tests --doctest-modules --pep8 qeez_stats -v --cov qeez_stats --cov-report term-missing
after_success:
  - coveralls

